parameters:
    # Models
    webburza_wishlist.model.wishlist.class: Webburza\Sylius\WishlistBundle\Model\Wishlist
    webburza_wishlist.model.wishlist_item.class: Webburza\Sylius\WishlistBundle\Model\WishlistItem

    # Front controllers
    webburza_wishlist.controller.front.wishlist.class: Webburza\Sylius\WishlistBundle\Controller\Frontend\WishlistController
    webburza_wishlist.controller.front.wishlist_item.class: Webburza\Sylius\WishlistBundle\Controller\Frontend\WishlistItemController

    # Account controllers
    webburza_wishlist.controller.account.wishlist.class: Webburza\Sylius\WishlistBundle\Controller\Account\WishlistController

    # Repositories
    webburza_wishlist.repository.wishlist.class: Webburza\Sylius\WishlistBundle\Doctrine\ORM\WishlistRepository
    webburza_wishlist.repository.wishlist_item.class: Webburza\Sylius\WishlistBundle\Doctrine\ORM\WishlistItemRepository

    # Plain factories
    webburza_wishlist.factory.plain.wishlist.class: Sylius\Component\Resource\Factory\Factory

    # Decorated factories
    webburza_wishlist.factory.wishlist.class: Webburza\Sylius\WishlistBundle\Factory\WishlistFactory

    # Listeners
    webburza_wishlist.listener.user.class: Webburza\Sylius\WishlistBundle\EventListener\UserListener
    webburza_wishlist.listener.menu_builder.class: Webburza\Sylius\WishlistBundle\EventListener\MenuBuilderListener
    webburza_wishlist.listener.menu_builder_account.class: Webburza\Sylius\WishlistBundle\EventListener\AccountMenuBuilderListener

    # Form Types
    webburza_wishlist.form.type.wishlist.class: Webburza\Sylius\WishlistBundle\Form\Type\WishlistType
    webburza_wishlist.form.type.admin_wishlist.class: Webburza\Sylius\WishlistBundle\Form\Type\AdminWishlistType
    webburza_wishlist.form.type.user_choice.class: Webburza\Sylius\WishlistBundle\Form\Type\UserChoiceType

    # Providers
    webburza_wishlist.provider.wishlist.class: Webburza\Sylius\WishlistBundle\Provider\WishlistProvider

    # Resolvers
    webburza_wishlist.resolver.product_variant_cart.class: Webburza\Sylius\WishlistBundle\Resolver\ProductVariantCartResolver

    # Twig
    webburza_wishlist.twig.wishlist_item.class: Webburza\Sylius\WishlistBundle\Twig\WishlistItemExtension

    # Remover
    webburza_wishlist.removed.expired_price_locks.class: Webburza\Sylius\WishlistBundle\Remover\ExpiredPriceLocksRemover